version: '3.8'

services:
  grafana:
    container_name: grafana
    build: 
      context: ./grafana
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - '$PWD/grafana/data:/var/lib/grafana'
    networks:
      - my-network

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}
    ports:
      - "80:80"
    volumes:
      - '$PWD/nginx/html:/usr/share/nginx/html'
    networks:
      - my-network

networks:
  my-network:
